
INSERT INTO boasaude_mic.USUARIO VALUES(1, 1, 00000000000, NOW(), NOW(), NULL, NULL, 'admin', NULL, 'Administrador', '$2a$10$mG6dB9/1fQXq/.KWPC/ALu1.qYjah1vJIMHkItYo00NkPVmeGGu8a', NULL, 0, NULL);
INSERT INTO boasaude_mic.USUARIO VALUES(2, 1, 00000000000, NOW(), NOW(), NULL, NULL, 'conveniado', NULL, 'Conveniado', '$2a$10$mG6dB9/1fQXq/.KWPC/ALu1.qYjah1vJIMHkItYo00NkPVmeGGu8a', NULL, 0, NULL);
INSERT INTO boasaude_mic.USUARIO VALUES(3, 1, 00000000000, NOW(), NOW(), NULL, NULL, 'prestador', NULL, 'Prestador', '$2a$10$mG6dB9/1fQXq/.KWPC/ALu1.qYjah1vJIMHkItYo00NkPVmeGGu8a', NULL, 0, NULL);
INSERT INTO boasaude_mic.USUARIO VALUES(4, 1, 00000000000, NOW(), NOW(), NULL, NULL, 'associado', NULL, 'Associado', '$2a$10$mG6dB9/1fQXq/.KWPC/ALu1.qYjah1vJIMHkItYo00NkPVmeGGu8a', NULL, 0, NULL);

INSERT INTO boasaude_mic.GRUPO VALUES (1, 'ADMINISTRADOR','ADMINISTRADOR');
INSERT INTO boasaude_mic.GRUPO VALUES (2, 'CONVENIADO','CONVENIADO');
INSERT INTO boasaude_mic.GRUPO VALUES (3, 'PRESTADOR','PRESTADOR');
INSERT INTO boasaude_mic.GRUPO VALUES (4, 'ASSOCIADO','ASSOCIADO');

INSERT INTO boasaude_mic.USUARIO_GRUPO VALUES(1, 1);
INSERT INTO boasaude_mic.USUARIO_GRUPO VALUES(2, 2);
INSERT INTO boasaude_mic.USUARIO_GRUPO VALUES(3, 3);
INSERT INTO boasaude_mic.USUARIO_GRUPO VALUES(4, 4);

INSERT INTO boasaude_mic.PERMISSAO VALUES(1, 'ADMINISTRADOR', 'ADMINISTRADOR', 'ADMINISTRADOR');
INSERT INTO boasaude_mic.PERMISSAO VALUES(2, 'CONVENIADO', 'CONVENIADO', 'CONVENIADO');
INSERT INTO boasaude_mic.PERMISSAO VALUES(3, 'PRESTADOR', 'PRESTADOR', 'PRESTADOR');
INSERT INTO boasaude_mic.PERMISSAO VALUES(4, 'ASSOCIADO', 'ASSOCIADO', 'ASSOCIADO');

INSERT INTO boasaude_mic.PERMISSAO_GRUPO VALUES(1,1);
INSERT INTO boasaude_mic.PERMISSAO_GRUPO VALUES(2,2);
INSERT INTO boasaude_mic.PERMISSAO_GRUPO VALUES(3,3);
INSERT INTO boasaude_mic.PERMISSAO_GRUPO VALUES(4,4);

INSERT INTO boasaude_mic.USUARIO_PERMISSAO VALUES(1,1);
INSERT INTO boasaude_mic.USUARIO_PERMISSAO VALUES(2,2);
INSERT INTO boasaude_mic.USUARIO_PERMISSAO VALUES(3,3);
INSERT INTO boasaude_mic.USUARIO_PERMISSAO VALUES(4,4);

INSERT INTO boasaude_mic.ESPECIALIDADE VALUES (1,'Acupuntura');
INSERT INTO boasaude_mic.ESPECIALIDADE VALUES (2,'Alergia e Imunologia');
INSERT INTO boasaude_mic.ESPECIALIDADE VALUES (3,'Anestesiologista');
INSERT INTO boasaude_mic.ESPECIALIDADE VALUES (4,'Angiologia');
INSERT INTO boasaude_mic.ESPECIALIDADE VALUES (5,'Cardiologia');
INSERT INTO boasaude_mic.ESPECIALIDADE VALUES (6,'Cirurgia Cardiovascular');
INSERT INTO boasaude_mic.ESPECIALIDADE VALUES (7,'Cirurgia de Mão');
INSERT INTO boasaude_mic.ESPECIALIDADE VALUES (8,'Cirurgia de Cabeça e Pescoço');
INSERT INTO boasaude_mic.ESPECIALIDADE VALUES (9,'Cirurgia do Aparelho Digestivo');
INSERT INTO boasaude_mic.ESPECIALIDADE VALUES (10,'Cirurgia Geral');


INSERT INTO boasaude_mic.PERFIL VALUES (1, NOW(), NOW(), 'ASSOCIADO', 'ASSOCIADO');
INSERT INTO boasaude_mic.PERFIL VALUES (2, NOW(), NOW(), 'PRESTADOR', 'PRESTADOR');
INSERT INTO boasaude_mic.PERFIL VALUES (3, NOW(), NOW(), 'CONVENIADO', 'CONVENIADO');
